---
minimum_pre_commit_version: 3.2.0
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    # renovate: datasource=git-tags depName=https://github.com/pre-commit/pre-commit-hooks depType=devDependencies
    rev: cef0300fd0fc4d2a87a85fa2093c6b283ea36f4b  # v5.0.0
    hooks:
      - id: trailing-whitespace
        args:
          - --markdown-linebreak-ext=md
      - id: mixed-line-ending
        args:
          - --fix=lf
        exclude: '^project/docs/make.bat$'
      - id: end-of-file-fixer
        exclude: '^project/docs/states.rst$'
      - id: check-merge-conflict
        args:
          - --assume-in-merge
      - id: check-yaml
      - id: check-ast
      - id: check-builtin-literals
      - id: debug-statements
        language_version: python3

  - repo: https://github.com/asottile/pyupgrade
    # renovate: datasource=git-tags depName=https://github.com/asottile/pyupgrade depType=devDependencies
    rev: 19364aa1b2ac289ce75e6bbe93994f7b4b9425f6  # v3.19.0
    hooks:
      - id: pyupgrade
        name: Rewrite code for Py3.9+
        args:
          - --py39-plus
        exclude: '^project'

  - repo: https://github.com/PyCQA/isort
    # renovate: datasource=git-tags depName=https://github.com/PyCQA/isort depType=devDependencies
    rev: c235f5e450b4b84e58d114ed4c589cbf454175a3  # 5.13.2
    hooks:
      - id: isort
        args:
          - --py=39
          - --profile=black
        exclude: '^project'

  - repo: https://github.com/psf/black
    # renovate: datasource=git-tags depName=https://github.com/psf/black depType=devDependencies
    rev: 1b2427a2b785cc4aac97c19bb4b9a0de063f9547  # 24.10.0
    hooks:
      - id: black
        name: Autoformat Python code
        args:
          - --target-version=py39
        exclude: '^project'
