---
project_name:
  type: str
  help: The name of the compose project.
  default: '{= abbr_pysafe =}'
  validator: >-
    {!- if not project_name !}
    Compose project name cannot be empty.
    {!- endif !}
  when: '{= flavor == "compose" =}'

containers:
  type: str
  help: A comma-separated list of container names that are part of the project.
  default: '{= abbr_pysafe =}'
  validator: >-
    {!- if not containers !}
    Containers cannot be empty.
    {!- endif !}
  when: '{= flavor == "compose" =}'
